Feature Leave Request
toggle-corp/tc-mis pull request #13
Opened 2021-01-18 04:35 UTC by nirojtogglecorp

Working on Leave Request function.

2021-01-27 06:45 UTC, annshress commented on employee/models.py
> +        return self.is_staff
In admin panel this is always true.

Furthermore, lets check for `self.is_active` flag as well.

2021-01-27 06:45 UTC, annshress commented on leave_request/admin.py
> +        employee_list = Employee.objects.exclude(id=request.user.id)
Maybe, we should limit request_to `HR`, `Admin` department only.

2021-01-27 06:45 UTC, annshress commented on leave_request/admin.py
> +        employee_list = Employee.objects.exclude(id=request.user.id)
Or further, we may not need `request_to`. 
All leave requests are accessible to people from specific departments like `HR` and `Admin`.

And I as an employee can only view my `leave requests` only.

2021-01-27 06:45 UTC, annshress commented on leave_request/admin.py
> +    queryset.update(status=1, verified_by_id=request.user.id)
```suggestion
    queryset.update(status=LeaveRequests.STATUSES.ACTIVE, verified_by_id=request.user.id)
```
is more readable.

2021-01-27 06:45 UTC, annshress commented on leave_request/admin.py
> +    queryset.update(status=0, verified_by_id=request.user.id)
`status=INACTIVE`

2021-01-27 06:45 UTC, annshress commented on leave_request/models.py
> +    request_to = models.ForeignKey(Employee, on_delete=models.DO_NOTHING, related_name="request_to")
What do you think about making these requests available to the department rather than employee? @nirojtogglecorp 

CC: @thenav56

2021-01-27 06:45 UTC, annshress commented on leave_request/models.py
> +            self.employee = get_current_authenticated_user()
I believe admin forms are the best place to handle these.

2021-01-27 06:45 UTC, annshress commented on leave_request/views.py
> +def actions(request):
Lets add permission for specific employees from certain departments only.

2021-01-27 06:45 UTC, annshress commented on leave_request/views.py
> +    if request.method == "POST":
Lets add permission for specific employees from certain departments only.

2021-01-27 10:34 UTC, nirojtogglecorp commented on leave_request/admin.py
> +        employee_list = Employee.objects.exclude(id=request.user.id)
request_to : to whom the request for, Suppose, I need leave and request to you. That means you and Hr can approve/reject it. Only you and HR can see the request.

2021-01-27 10:46 UTC, nirojtogglecorp commented on leave_request/admin.py
> +    queryset.update(status=0, verified_by_id=request.user.id)
Good catch. Fixed to LeaveRequest.STATUSES.INACTIVE

2021-01-27 10:46 UTC, nirojtogglecorp commented on leave_request/admin.py
> +    queryset.update(status=1, verified_by_id=request.user.id)
Fixed to LeaveRequest.STATUSES.ACTIVE

2021-01-27 10:47 UTC, nirojtogglecorp commented on employee/models.py
> +        return self.is_staff
Fixed. return self.is_staff

2021-02-01 05:10 UTC, thenav56 requested changes

2021-02-01 05:10 UTC, thenav56 commented on leave_request/admin.py
> +            self.list_display = "employee"
Do we need this? We are already overwriting get_list_display().

2021-02-01 05:10 UTC, thenav56 commented on leave_request/models.py
> +        admin_employee = Employee.objects.filter(is_superuser=1, is_active=1).exclude(id=get_current_authenticated_user().id)
`is_superuser` and `is_active` are boolean fields so let's use boolean value instead of an integer.

2021-02-01 05:10 UTC, thenav56 commented on leave_request/models.py
> +                [to]
`to` is already an array. Do we need to do this?

2021-02-01 05:10 UTC, thenav56 commented on leave_request/models.py
> +    request_to = models.ForeignKey(Employee, on_delete=models.DO_NOTHING, related_name="request_to")
Sounds good.

CC: @amarshahi

2021-02-01 10:01 UTC, amarshahi commented on leave_request/models.py
> +    request_to = models.ForeignKey(Employee, on_delete=models.DO_NOTHING, related_name="request_to")
When an employee sends a leave request, it should trigger an email to the HR and the employee's manager.

2021-02-01 10:54 UTC, nirojtogglecorp commented on leave_request/models.py
> +                [to]
Removed

2021-02-01 10:54 UTC, nirojtogglecorp commented on leave_request/admin.py
> +            self.list_display = "employee"
Removed and Tested.

2021-02-01 10:54 UTC, nirojtogglecorp commented on leave_request/admin.py
> +        return True
Thanks.

2021-02-01 10:54 UTC, nirojtogglecorp commented on leave_request/admin.py
> +        form.base_fields['start_date'].initial = datetime.datetime.now()
Added timezone

2021-02-01 10:54 UTC, nirojtogglecorp commented on leave_request/admin.py
> +        return "start_date", 'end_date', "leave_type", "leave_details", "request_to", "reason_for_leave", "header_status"
Thanks.

2021-02-01 10:55 UTC, nirojtogglecorp commented on leave_request/models.py
> +        if self.status == 0:
Changed to self.STATUSES.INACTIVE

2021-02-01 10:55 UTC, nirojtogglecorp commented on leave_request/models.py
> +    class LEAVETYPES(enum.Enum):
Used CamelCase for Classes.

2021-02-02 05:42 UTC, thenav56 requested changes

2021-02-02 08:13 UTC, nirojtogglecorp commented on leave_request/models.py
> +        admin_employee = Employee.objects.filter(is_superuser=1, is_active=1).exclude(id=get_current_authenticated_user().id)
Added boolean

2021-02-02 08:14 UTC, nirojtogglecorp commented on leave_request/models.py
> +    class STATUSES(enum.Enum):
changed To Statuses

2021-02-02 09:40 UTC, nirojtogglecorp commented on leave_request/admin.py
> +        content = "Your request has been approved from {start_date} to {end_date} ." \
Used like  f"Your request has been approved from {start_date} to {end_date} ."

2021-02-02 09:41 UTC, nirojtogglecorp commented on leave_request/views.py
> +    if request.method == "POST":
The list will displayed only for the superuser and the request_to user.

2021-02-02 09:41 UTC, nirojtogglecorp commented on leave_request/views.py
> +def actions(request):
The list will displayed only for the superuser and the request_to user.

2021-02-02 09:42 UTC, nirojtogglecorp commented on leave_request/models.py
> +            self.employee = get_current_authenticated_user()
It has been removed and django_current user is used in model.

2021-02-02 09:43 UTC, nirojtogglecorp commented on leave_request/models.py
> +    request_to = models.ForeignKey(Employee, on_delete=models.DO_NOTHING, related_name="request_to")
Yes, it sends email to superuser and request_to user. Here employee's manager can be anyone from the same department.

2021-02-03 03:27 UTC, annshress approved these changes

2021-02-03 12:37 UTC, nirojtogglecorp commented on leave_request/models.py
> +            self.employee = get_current_authenticated_user()
It has been used in model. not needed here.

2021-02-04 04:13 UTC, thenav56 approved these changes

2021-02-04 07:11 UTC, merged