Added Docker File
toggle-corp/tc-mis pull request #15
Opened 2021-01-27 04:44 UTC by nirojtogglecorp

DockerFile and compose has been added.

Stil looking how aws is used.

2021-01-27 05:44 UTC, thenav56 requested changes

2021-01-27 05:44 UTC, thenav56 commented on Dockerfile
> +COPY . .
Let's not use alpine. Alpine images are not that stable. `buster-slim` should be the best choice for now.
And `COPY . .` should be `COPY . /code/`

Also, let's go throw this article for further improvements.
https://www.docker.com/blog/intro-guide-to-dockerfile-best-practices/

2021-01-27 05:44 UTC, thenav56 commented on docker-compose.yml
> +      - POSTGRES_DB=mis
Let's first define db and then web. Since web depends on db.
```suggestion
  db:
    image: library/postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=mis
      
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8081
    volumes:
      - .:/app
    ports:
      - 8082:8081
    depends_on:
       - db
```

2021-01-27 10:13 UTC, nirojtogglecorp commented on Dockerfile
> +COPY . .
Convert to slim buster.
COPY . /app/

2021-01-27 10:13 UTC, nirojtogglecorp commented on docker-compose.yml
> +      - POSTGRES_DB=mis
Defined db first.

2021-01-27 10:31 UTC, thenav56 requested changes

2021-01-27 10:31 UTC, thenav56 commented on docker-compose.yml
> +      - POSTGRES_PASSWORD=P'T/4Nk6`T-+tSzL
A simple password is enough. Let's also update Readme specifying docker-compose.yml should only be used for development.

2021-01-27 10:31 UTC, thenav56 commented on Dockerfile
> +RUN pip install --no-cache-dir -r /app/requirements.txt
Let's change the Dockerfile to this.

```suggestion
# pull official base image
FROM python:3.9.1-slim-buster

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update \
    && apt-get -y install \
    && apt-get -y install postgresql postgresql-contrib build-essential \
    && pip install --upgrade pip \
    && rm -rf /var/lib/apt/lists/*

# set work directory
WORKDIR /code

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . ./
```

Installing the python package at the end will always trigger the pip install. Basically, docker will clear build-cache after `COPY . /app/`, so we need to install python requirement before. Also `COPY requirements.txt /app/` will ensure to clear cache if requirements.txt is changed.

Also, I made a mistake, we can use `COPY . ./` here. So we can use "./" instead of "/app" too.

Also, If there is no issue can we use /code instead of /app? We are using `/code` for most of the projects, just for consistency.

2021-01-27 11:27 UTC, nirojtogglecorp commented on docker-compose.yml
> +      - POSTGRES_PASSWORD=P'T/4Nk6`T-+tSzL
Password change and added README.md file

2021-01-27 11:27 UTC, nirojtogglecorp commented on Dockerfile
> +RUN pip install --no-cache-dir -r /app/requirements.txt
Changed as suggested.

2021-01-27 12:36 UTC, thenav56 commented on Dockerfile
> +RUN pip install --no-cache-dir -r /app/requirements.txt
`COPY . /` will copy to root directory. We need this `COPY . ./`

2021-01-27 13:11 UTC, thenav56 requested changes

2021-01-27 13:11 UTC, thenav56 commented on README.md
> +docker ps
We don't have to go into in-depth details here. Basic commands should be enough.
```bash
docker-compose build  # initial setup or Dockerfile is changed, make sure to update the containers with `docker-compose up -d` after a successful build
docker-compose up  # To start the containers and view the logs. CTRL+C to stop the containers.
docker-compose up -d  # Starting the containers in detach mode
docker-compose logs -f  # To view containers logs, we can also specify service here.

docker-compose down  # To stop and remove the containers
docker-compose stop|start|restart  # To stop|start|restart containers, we can also specify service here. NOTE: restart will not update the container's image.

docker-compose exec web sh  # To attach to container shell
docker-compose exec web python3 manage.py createsuperuser  # To run commands directly inside the container

docker-compose -f docker-compose-custom.yml {COMMANDS}  # For custom compose file
```
For more, `docker-compose -h` or https://docs.docker.com/compose/reference/

Also, let's include this
> Current docker-compose.yml is only meant for local development. Don't use it in production. Define a custom compose file **production-compose.yml** and use it with `docker-compose -f production-compose.yml` in production.

Also, instead of using `-p` we should define it inside docker-compose.yml. For now, let's stick with the default.

2021-01-28 05:41 UTC, nirojdyola commented on Dockerfile
> +RUN pip install --no-cache-dir -r /app/requirements.txt
Changed to ./

2021-01-28 05:42 UTC, nirojdyola commented on README.md
> +docker ps
Removed the existing content and updated with the given text.
Since copied the same text is not readable, have  slightly changed the view.

2021-01-28 08:20 UTC, thenav56 approved these changes

2021-01-28 16:14 UTC, merged