Add requirement.txt file
toggle-corp/tc-mis pull request #9
Opened 2021-01-13 06:28 UTC by nirojtogglecorp

Added requirement.txt file
It defines what packages you have installed during development.

2021-01-13 07:25 UTC, annshress requested changes
Should be `requirements.txt`

2021-01-15 11:32 UTC, annshress requested changes

2021-01-15 11:32 UTC, annshress commented on requirement.txt
> +django-currentuser==0.5.2
Lets delete this file.

2021-01-18 05:00 UTC, nirojtogglecorp commented on requirement.txt
> +django-currentuser==0.5.2
File has been deleted.

2021-01-18 07:41 UTC, merged